version: '3'

networks:
    bibbox-default-network:
      external: true

services:

  bibbox-jenkins:
    image: jenkins/jenkins:2.411
    container_name:  bibbox-jenkins
    restart: unless-stopped
    networks:
      - bibbox-default-network
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./data/:/var/jenkins_home

